import { AppCategory, AppItem, RelatedAppItem } from "@/types/store";

export const CATEGORIES: AppCategory[] = [
  "Semua",
  "Produktivitas",
  "Pendidikan",
  "Bisnis",
  "Multimedia",
  "Utility",
  "Game",
];

export const APP_STORE_ITEMS: AppItem[] = [
  {
    id: "notely",
    name: "Notely",
    tagline: "Aplikasi Pencatat Modern & Sinkronisasi Cepat",
    description: "Aplikasi pencatat cepat dan mudah dengan fitur sinkronisasi cloud.",
    longDescription:
      "Notely adalah aplikasi pencatat modern yang dirancang untuk membantu kamu mencatat ide, tugas, dan catatan penting dengan mudah dan cepat. Dilengkapi dengan fitur sinkronisasi cloud, sehingga data kamu selalu aman dan dapat diakses di semua perangkat.",
    category: "Produktivitas",
    rating: 4.8,
    reviewsCount: "1.2K ulasan",
    fileSize: "12.5 MB",
    version: "2.1.0",
    developer: "AppHub Studio",
    lastUpdated: "14 September 2026",
    platforms: ["android"],
    iconType: "document",
    iconColor: "bg-blue-500",
    downloadsCount: "500K+",
    features: [
      "Membuat dan mengelola catatan",
      "Sinkronisasi cloud antar perangkat",
      "Pengingat tugas dan jadwal",
      "Mode terang dan gelap",
      "Mendukung berbagai format (teks, checklist, dll)",
    ],
    screenshots: [
      {
        id: "s1",
        title: "Semua Catatan",
        description: "Daftar catatan rapi dengan pencarian instan dan kategori folder.",
        type: "light",
      },
      {
        id: "s2",
        title: "Editor Catatan",
        description: "Editor teks kaya dengan toolbar format dan daftar periksa.",
        type: "editor",
      },
      {
        id: "s3",
        title: "Kalender & Jadwal",
        description: "Tampilan kalender terintegrasi dengan penanda deadline tugas.",
        type: "calendar",
      },
      {
        id: "s4",
        title: "Semua Catatan (Dark Mode)",
        description: "Mode gelap kontras tinggi untuk kenyamanan mata di malam hari.",
        type: "dark",
      },
    ],
    systemRequirements: {
      os: "Android 8.0 ke atas",
      ram: "Minimum 2 GB RAM",
      storage: "50 MB ruang penyimpanan bebas",
    },
  },
  {
    id: "edulearn",
    name: "EduLearn",
    tagline: "Platform Belajar Daring Interaktif",
    description: "Platform belajar online dengan berbagai materi edukasi.",
    longDescription:
      "EduLearn menghadirkan ribuan materi pembelajaran interaktif, kursus video beresolusi tinggi, dan latihan soal terstruktur untuk siswa maupun profesional.",
    category: "Pendidikan",
    rating: 4.7,
    reviewsCount: "950 ulasan",
    fileSize: "25.3 MB",
    version: "3.0.2",
    developer: "EduTech Global",
    lastUpdated: "10 September 2026",
    platforms: ["android"],
    iconType: "education",
    iconColor: "bg-emerald-500",
    downloadsCount: "350K+",
    features: [
      "Ribuan video materi belajar interaktif",
      "Kuis adaptif dengan pembahasan lengkap",
      "Sertifikat kelulusan terverifikasi",
      "Mode unduh video untuk ditonton offline",
    ],
    screenshots: [
      { id: "e1", title: "Katalog Kursus", description: "Pilihan topik lengkap", type: "light" },
      { id: "e2", title: "Pemutar Video", description: "Video HD & subtitle", type: "editor" },
      { id: "e3", title: "Kuis Interaktif", description: "Evaluasi pemahaman", type: "calendar" },
      { id: "e4", title: "Sertifikat", description: "Pencapaian belajar", type: "dark" },
    ],
    systemRequirements: {
      os: "Android 8.0 ke atas",
      ram: "Minimum 2 GB RAM",
      storage: "80 MB ruang penyimpanan",
    },
  },
  {
    id: "kasirpro",
    name: "KasirPro",
    tagline: "Aplikasi POS & Manajemen Kasir Bisnis",
    description: "Aplikasi kasir sederhana untuk mengelola transaksi bisnis.",
    longDescription:
      "KasirPro mempermudah pencatatan penjualan kasir (POS), inventaris stok barang secara otomatis, dan pelaporan laba rugi harian untuk UMKM.",
    category: "Bisnis",
    rating: 4.6,
    reviewsCount: "820 ulasan",
    fileSize: "18.7 MB",
    version: "1.8.4",
    developer: "Nusantara POS",
    lastUpdated: "08 September 2026",
    platforms: ["android"],
    iconType: "business",
    iconColor: "bg-purple-600",
    downloadsCount: "200K+",
    features: [
      "Pencatatan transaksi kasir kilat",
      "Cetak struk via printer thermal Bluetooth",
      "Manajemen stok dan peringatan barang habis",
      "Laporan penjualan harian dan bulanan",
    ],
    screenshots: [
      { id: "k1", title: "Menu Kasir", description: "Pilihan produk cepat", type: "light" },
      { id: "k2", title: "Struk Pembayaran", description: "Cetak nota instan", type: "editor" },
      { id: "k3", title: "Inventaris Stok", description: "Laporan gudang", type: "calendar" },
      { id: "k4", title: "Analitik Penjualan", description: "Grafik laba rugi", type: "dark" },
    ],
    systemRequirements: {
      os: "Android 7.0 ke atas",
      ram: "Minimum 2 GB RAM",
      storage: "40 MB ruang penyimpanan",
    },
  },
  {
    id: "photoeditor",
    name: "PhotoEditor",
    tagline: "Editor Foto Kreatif & Filter Profesional",
    description: "Edit foto dengan mudah dan hasil berkualitas tinggi.",
    longDescription:
      "PhotoEditor menyediakan alat manipulasi gambar profesional, ratusan preset filter estetik, penghapus latar belakang instan berbasis AI, dan pengaturan kurva warna.",
    category: "Multimedia",
    rating: 4.5,
    reviewsCount: "2.1K ulasan",
    fileSize: "32.1 MB",
    version: "4.2.0",
    developer: "PixelCraft Lab",
    lastUpdated: "05 September 2026",
    platforms: ["android"],
    iconType: "photo",
    iconColor: "bg-amber-500",
    downloadsCount: "1M+",
    features: [
      "Penghapus latar belakang otomatis satu ketukan",
      "Koleksi 150+ filter dan efek foto artistik",
      "Pengaturan kurva tone, saturasi, dan eksposur",
      "Ekspor format resolusi tinggi tanpa kompresi berlebih",
    ],
    screenshots: [
      { id: "p1", title: "Kanvas Edit", description: "Ruang kerja intuitif", type: "light" },
      { id: "p2", title: "Pilihan Filter", description: "Efek visual estetik", type: "editor" },
      { id: "p3", title: "Koreksi Warna", description: "Penyesuaian kurva pro", type: "calendar" },
      { id: "p4", title: "Ekspor Galeri", description: "Format HD & PNG", type: "dark" },
    ],
    systemRequirements: {
      os: "Android 8.0 ke atas",
      ram: "Minimum 4 GB RAM",
      storage: "120 MB ruang penyimpanan",
    },
  },
  {
    id: "securevpn",
    name: "SecureVPN",
    tagline: "Perlindungan Privasi Online Berkecepatan Tinggi",
    description: "VPN aman dan cepat untuk melindungi privasi online.",
    longDescription:
      "SecureVPN melindungi data berselancar internet Anda dengan enkripsi kelas militer WireGuard, tanpa pencatatan log riwayat (no-log policy), dan server di 60+ negara.",
    category: "Utility",
    rating: 4.7,
    reviewsCount: "3.4K ulasan",
    fileSize: "16.8 MB",
    version: "2.5.1",
    developer: "ShieldNet Security",
    lastUpdated: "12 September 2026",
    platforms: ["android"],
    iconType: "vpn",
    iconColor: "bg-blue-600",
    downloadsCount: "2M+",
    features: [
      "Protokol WireGuard & OpenVPN terenkripsi 256-bit",
      "Kebijakan ketat tanpa log riwayat (No-Log Policy)",
      "Fitur Kill Switch otomatis saat koneksi terputus",
      "Bandwidth tak terbatas dengan server latensi rendah",
    ],
    screenshots: [
      { id: "v1", title: "Koneksi Cepat", description: "Sambungan 1-klik", type: "light" },
      { id: "v2", title: "Daftar Server", description: "60+ lokasi global", type: "editor" },
      { id: "v3", title: "Uji Kecepatan", description: "Monitor latensi real-time", type: "calendar" },
      { id: "v4", title: "Pengaturan Keamanan", description: "Kill switch & DNS", type: "dark" },
    ],
    systemRequirements: {
      os: "Android 7.0 ke atas",
      ram: "Minimum 1 GB RAM",
      storage: "30 MB ruang penyimpanan",
    },
  },
  {
    id: "gamezone",
    name: "GameZone",
    tagline: "Koleksi Game Santai & Arcade Seru",
    description: "Kumpulan game seru dalam satu aplikasi.",
    longDescription:
      "GameZone mengumpulkan puluhan game arcade, teka-teki logika, dan petualangan santai yang dapat dimainkan secara langsung tanpa perlu instalasi terpisah.",
    category: "Game",
    rating: 4.4,
    reviewsCount: "1.8K ulasan",
    fileSize: "45.2 MB",
    version: "1.2.0",
    developer: "ArcadePlay Inc",
    lastUpdated: "01 September 2026",
    platforms: ["android"],
    iconType: "game",
    iconColor: "bg-indigo-600",
    downloadsCount: "800K+",
    features: [
      "50+ mini game arcade dan teka-teki logika",
      "Papan peringkat skor global harian dan mingguan",
      "Dukungan kontroler gamepad Bluetooth",
      "Mode permainan offline tanpa koneksi internet",
    ],
    screenshots: [
      { id: "g1", title: "Lobi Game", description: "Pilihan permainan arcade", type: "light" },
      { id: "g2", title: "Gameplay Seru", description: "Grafis responsif 60fps", type: "editor" },
      { id: "g3", title: "Leaderboard", description: "Peringkat skor pemain", type: "calendar" },
      { id: "g4", title: "Pencapaian", description: "Trofi & hadiah harian", type: "dark" },
    ],
    systemRequirements: {
      os: "Android 8.0 ke atas",
      ram: "Minimum 3 GB RAM",
      storage: "150 MB ruang penyimpanan",
    },
  },
  {
    id: "clouddrive",
    name: "CloudDrive",
    tagline: "Penyimpanan Berkas Awan Pribadi & Aman",
    description: "Penyimpanan cloud untuk mengakses file kapan saja.",
    longDescription:
      "CloudDrive menyediakan penyimpanan awan terenkripsi untuk mencadangkan foto, dokumen kerja, dan video penting dengan sinkronisasi otomatis antar perangkat.",
    category: "Produktivitas",
    rating: 4.6,
    reviewsCount: "1.5K ulasan",
    fileSize: "20.3 MB",
    version: "3.1.0",
    developer: "CloudCore Tech",
    lastUpdated: "03 September 2026",
    platforms: ["android"],
    iconType: "cloud",
    iconColor: "bg-sky-500",
    downloadsCount: "600K+",
    features: [
      "Kapasitas penyimpanan awan aman hingga 50 GB",
      "Berbagi berkas melalui tautan dengan perlindungan sandi",
      "Pencadangan otomatis galeri foto dan video",
      "Pratinjau dokumen PDF, Office, dan gambar langsung",
    ],
    screenshots: [
      { id: "c1", title: "Daftar Berkas", description: "Manajemen folder intuitif", type: "light" },
      { id: "c2", title: "Unggah Dokumen", description: "Proses transfer cepat", type: "editor" },
      { id: "c3", title: "Berbagi Tautan", description: "Hak akses terlindungi", type: "calendar" },
      { id: "c4", title: "Pencadangan Otomatis", description: "Sinkronisasi background", type: "dark" },
    ],
    systemRequirements: {
      os: "Android 8.0 ke atas",
      ram: "Minimum 2 GB RAM",
      storage: "60 MB ruang penyimpanan",
    },
  },
  {
    id: "streambox",
    name: "StreamBox",
    tagline: "Pemutar Media & Hiburan Video Favorit",
    description: "Nonton film dan serial favorit dimanapun.",
    longDescription:
      "StreamBox adalah aplikasi pemutar media dan streaming konten berkualitas tinggi dengan dukungan subtitle multi-bahasa, audio spasial, dan antarmuka ramah pengguna.",
    category: "Multimedia",
    rating: 4.5,
    reviewsCount: "4.2K ulasan",
    fileSize: "28.7 MB",
    version: "2.9.0",
    developer: "StreamFlix Media",
    lastUpdated: "11 September 2026",
    platforms: ["android"],
    iconType: "media",
    iconColor: "bg-red-500",
    downloadsCount: "3M+",
    features: [
      "Pemutaran video resolusi Ultra HD 4K dan HDR10",
      "Dukungan subtitle eksternal (SRT, VTT, ASS)",
      "Mode Picture-in-Picture (PiP) multitasking",
      "Pilihan kualitas streaming adaptif hemat kuota data",
    ],
    screenshots: [
      { id: "m1", title: "Koleksi Video", description: "Katalog film & serial", type: "light" },
      { id: "m2", title: "Pemutar 4K", description: "Kontrol gestur audio & terang", type: "editor" },
      { id: "m3", title: "Daftar Putar", description: "Tonton nanti & riwayat", type: "calendar" },
      { id: "m4", title: "Pengaturan Audio", description: "Equalizer & suara jernih", type: "dark" },
    ],
    systemRequirements: {
      os: "Android 8.0 ke atas",
      ram: "Minimum 3 GB RAM",
      storage: "90 MB ruang penyimpanan",
    },
  },
];

export const RELATED_APPS: RelatedAppItem[] = [
  {
    id: "taskmaster",
    name: "TaskMaster",
    rating: 4.6,
    fileSize: "18.2 MB",
    category: "Produktivitas",
    iconType: "task",
    iconColor: "bg-blue-600",
  },
  {
    id: "notepro",
    name: "NotePro",
    rating: 4.5,
    fileSize: "14.7 MB",
    category: "Produktivitas",
    iconType: "note",
    iconColor: "bg-purple-600",
  },
  {
    id: "todoplus",
    name: "TodoPlus",
    rating: 4.4,
    fileSize: "10.3 MB",
    category: "Produktivitas",
    iconType: "todo",
    iconColor: "bg-sky-500",
  },
];

export const APP_CONFIG = {
  name: "AppHub",
  tagline: "Katalog & Unduh Aplikasi Android APK Terpercaya",
  version: "2.4.0",
  currentVersion: "v2.4.0",
  releaseDate: "14 September 2026",
  shortDescription:
    "Aplikasi produktivitas dan catatan harian cerdas dengan sinkronisasi instan, antarmuka modern, dan privasi penuh.",
  fileSize: "28.4 MB",
  minAndroid: "Android 8.0+",
  sha256: "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
  apkFileName: "apphub-v2.4.0-release.apk",
  downloadUrl: "https://github.com/Aldikurniawan19/app-release/releases/download/apk-releases/apphub-v2.4.0-release.apk",
  downloadApkUrl: "https://github.com/Aldikurniawan19/app-release/releases/download/apk-releases/apphub-v2.4.0-release.apk",
  playStoreUrl: "https://play.google.com/store/apps",
  githubUrl: "https://github.com/Aldikurniawan19/app-release",
};

export const INSTALLATION_STEPS = [
  {
    step: "01",
    title: "Unduh Berkas APK",
    description: "Klik tombol Download dan simpan berkas APK resmi di penyimpanan ponsel Anda.",
  },
  {
    step: "02",
    title: "Izinkan Sumber Tak Dikenal",
    description: "Buka Pengaturan > Keamanan, lalu aktifkan opsi 'Izinkan pemasangan dari sumber ini'.",
  },
  {
    step: "03",
    title: "Buka & Pasang Aplikasi",
    description: "Buka berkas APK melalui Pengelola File atau notifikasi unduhan, lalu tekan Pasang.",
  },
  {
    step: "04",
    title: "Selesai & Siap Digunakan",
    description: "Buka aplikasi langsung dari layar utama perangkat Anda dan nikmati seluruh fiturnya.",
  },
];

export const STORE_BENEFITS = [
  {
    title: "Bebas Malware & Aman",
    description: "Semua paket APK dipindai secara ketat sebelum diterbitkan ke katalog.",
  },
  {
    title: "Unduhan Cepat & Tanpa Iklan",
    description: "Server unduhan berkecepatan tinggi langsung ke perangkat Anda.",
  },
  {
    title: "Pembaruan Versi Teratur",
    description: "Dapatkan rilis dan fitur terbaru secara instan tanpa hambatan.",
  },
];

